Add RemoveProblemReducer test
enspyrco/the_process pull request #22
Opened 2021-02-09 00:53 UTC by T-Davis

RemoveProblemReducer unit test
Part of [UC10](https://docs.google.com/document/d/1WONN5L97YWlA3-9ZdlM6vQcmBx36m-aGm5xcjb-t16w/edit#heading=h.k3l9rzap2hfx) Dismiss ProblemPage

2021-02-09 01:23 UTC, nickmeinhold requested changes
Awesome work mate!! 

Can we discuss our policy on unrelated changes in PRs - I'd love to get clear on an agreement that doesn't create too much overhead or become too burdensome but doesn't let us get too far down a path that ends in messy PRs without clear boundaries.  

In this case the xcconfig files I would love to have in a separate PR (or just discuss and leave them in this one) - I've seen the change on my end too and wouldn't mind pausing to understand where it came from if possible.  

Changing integration_test to SDK import - I know we've discussed it but I think we should try and remind each other to at least comment on unrelated changes so the PR includes the note on where the change came from.  

It's hypocritical of me given a lot of my PRs have included lots of unrelated stuff but I figure let's try and pull each other up, assuming we agree on a policy of (say) unrelated changes should be moved out where it makes sense or commented on when it doesn't.  

Thanks mate!

2021-02-11 00:43 UTC, T-Davis commented on pubspec.yaml
>    integration_test:
This dependency is now included in the Flutter SDK, thus doesn't need to be gotten from pub.dev

2021-02-11 01:11 UTC, T-Davis commented
@nickmeinhold Great call out mate! Always want to be making better PRs.
I think the policy is as you expected (just not followed on my end) that the committed code should be relevant to the PR, and any code that isn't clearly relevant should be commented on to explain why it's relevant. 👍 
Thanks a ton! 🙏

2021-02-11 04:24 UTC, nickmeinhold submitted a review, later dismissed
Awesome work mate!  I just had the one super nit

2021-02-11 04:24 UTC, nickmeinhold commented on test/sections/error-handling/UC10/remove_problem_reducer_unit_test.dart
> +        'Removes Problem from appState.problems and ProblemPageData from appState.pagesData',
```suggestion
        'removes Problem from appState.problems and ProblemPageData from appState.pagesData',
```

Uber nit - the string in group('... is the start of the sentence and the string in test('... is the continuation of the sentence so should start lower case.

2021-02-11 04:25 UTC, nickmeinhold approved these changes

2021-02-11 04:27 UTC, nickmeinhold commented
@T-Davis I committed the nit and Approved my own change to save time... now that I type that out loud, that's probably not appropriate.  Let me know if you have any concerns.  Thanks mate!

2021-02-11 04:27 UTC, merged