Fix Android runtime errors
enspyrco/the_process pull request #28
Opened 2021-02-19 13:22 UTC by nickmeinhold

* Update & remove redundant dependencies
- removed unused firebase_messaging package to hopefully avoid
version conflicts
- updated gradle, compileSDKVersion, targetSDKVersion

2021-02-21 23:01 UTC, T-Davis commented on lib/utils/wrappers/firebase_wrapper.dart
>  /// the [CrowdLeagueApp] widget.
Small nit for CrowdLeagueApp

2021-02-21 23:03 UTC, T-Davis commented on lib/utils/wrappers/firebase_wrapper.dart
> +    // TODO: remove workaround
Apologies if this was already explained, but could you tell me what this workaround is for?

2021-02-21 23:05 UTC, T-Davis requested changes
Thanks for the PR!
I left a couple of comments to address

2021-02-22 04:35 UTC, nickmeinhold commented on lib/utils/wrappers/firebase_wrapper.dart
>  /// the [CrowdLeagueApp] widget.
Thanks mate!  Do you think we should agree to try and make these nits as "suggested changes", probably ends up being less work right, given that you're already at the code to make the suggestion?   I'll do it now, just to be clear, just thinking for  the future

2021-02-22 04:42 UTC, nickmeinhold commented on lib/utils/wrappers/firebase_wrapper.dart
>  /// the [CrowdLeagueApp] widget.
```suggestion
/// the [AppWidget].
```

2021-02-22 04:42 UTC, nickmeinhold commented on lib/utils/wrappers/firebase_wrapper.dart
> +    // TODO: remove workaround
No worries!  Yeah we discussed this morning - it's the crash due to NNBD Firestore.  The url was indeed in one of the commits... one win among many losses my ailing memory :-) FirebaseExtended/flutterfire#4948

2021-02-22 04:43 UTC, nickmeinhold commented on lib/utils/wrappers/firebase_wrapper.dart
> +    // TODO: remove workaround
I went ahead and committed the change, not sure if that was protocol... happy to be corrected!

2021-02-22 04:44 UTC, nickmeinhold reviewed
I think it's good when you're ready mate!

2021-02-22 05:47 UTC, T-Davis commented on lib/utils/wrappers/firebase_wrapper.dart
>  /// the [CrowdLeagueApp] widget.
Yep, definitely! I should've

2021-02-22 05:49 UTC, T-Davis commented on lib/utils/wrappers/firebase_wrapper.dart
> +    // TODO: remove workaround
All good! Better to have a working app I reckon 😉

2021-02-22 05:50 UTC, T-Davis approved these changes
Looks great! Thanks for getting us back up and running 👍

2021-02-22 05:50 UTC, merged