Ensure-middleware-catches-errors
enspyrco/the_process pull request #32
Opened 2021-02-22 05:35 UTC by T-Davis

Added a try-catch for all middleware

2021-02-22 06:14 UTC, nickmeinhold commented
Thanks @T-Davis!  Reporting on discussion: we decided including tests here is a good idea, so I will remove myself from review

2021-03-26 23:55 UTC, T-Davis commented on lib/actions/shared/connect_database_action.dart
> +import 'package:freezed_annotation/freezed_annotation.dart';
I updated the file to include 'Action', that's why it's all green

2021-03-26 23:57 UTC, T-Davis commented on lib/middleware/app_middleware.dart
>  import 'package:the_process/middleware/auth/sign_in_with_google.dart';
There are a couple of these name changes that I included in the PR, because I was already touching the file.
Happy to pull these changes out into their own PR if you think so

Effective Dart:
DO capitalize acronyms and abbreviations longer than two letters like words.

2021-03-27 00:13 UTC, nickmeinhold commented on lib/middleware/app_middleware.dart
>  import 'package:the_process/middleware/auth/sign_in_with_google.dart';
Sounds like you're saying "because I was already touching the file" is a reason to also make a name change but I would definitely say the opposite - "because I was already touching the file" is a good reason *not* to make a name change in the same PR, because the changes get lost.  The question of is it worth breaking out into a separate PR is a different question of course, but thought the reasoning was worth clarifying.

The Effective Dart reference is (I assume) in reference to the URL -> Url change - I'm pretty sure we've had this discussion before - we are following Effective Dart where there are not opposing style guides rules we've adopted - this is one where there is (potentially) a valid reason to do something different because Firebase uses a bunch of 'URL' in file names so we have choose between a few sucky choices - I believe we ended up agreeing that the least sucky choice was to follow Firebase in the case of a variable ending in URL.  I'll check if the style guide includes what my memory says we agreed on and comment here...

2021-03-27 00:31 UTC, T-Davis commented on lib/middleware/app_middleware.dart
>  import 'package:the_process/middleware/auth/sign_in_with_google.dart';
I think your first point is a good enough reason for me to break out those changes. Also, to your second point, damn my memory!

2021-03-27 00:34 UTC, nickmeinhold requested changes
Awesome work @T-Davis!  I had a couple of suggestions - if anything isn't clear I'm happy to clarify at the meetup, or via comments if you won't be at the meetup.  Thanks heaps!

2021-03-27 00:34 UTC, nickmeinhold commented on lib/actions/shared/connect_database_action.dart
> +import 'package:freezed_annotation/freezed_annotation.dart';
Got it, thanks!

2021-03-27 00:34 UTC, nickmeinhold commented on test/redux/middleware_unit_test.dart
> +      expect(store.dispatchedActions[0].runtimeType.toString(),
So we can't do: `expect(store.dispatchedActions[0].runtimeType, AddProblemAction)`? what about `expect(store.dispatchedActions[0] is AddProblemAction, true)`?  I haven't played with the options but just wondering as comparing the strings like this just seems less clear and more error prone.

2021-03-27 00:34 UTC, nickmeinhold commented on test/redux/middleware_unit_test.dart
> +      expect(store.dispatchedActions[0].runtimeType.toString(),
Oh right, just read your comment, nice one - yeah so I imagine my first option won't work but the second one should I think?

2021-03-27 00:34 UTC, nickmeinhold commented on test/redux/middleware_unit_test.dart
> +      expect(store.dispatchedActions[0].runtimeType.toString(),
Another option would be a type matcher: https://api.flutter.dev/flutter/package-matcher_matcher/TypeMatcher-class.html

2021-03-27 00:34 UTC, nickmeinhold commented on test/redux/middleware_unit_test.dart
> +  group('Middleware catches errors', () {
Because the output of running the tests from command line uses Group Name -> Test name I always try and make the combination be an easily readable sentence (main reason being it makes scanning the CI output a lot easier)

2021-03-27 00:40 UTC, T-Davis commented
> if anything isn't clear I'm happy to clarify at the meetup

I'll see you there!

2021-03-27 01:40 UTC, nickmeinhold commented on lib/middleware/app_middleware.dart
>  import 'package:the_process/middleware/auth/sign_in_with_google.dart';
Sorry mate, I should have added - personally I would say don't worry about pulling out changes now, it's more hassle than it's worth here imo.  I just wanted to clarify to make sure we're on the same page in regards to the reasoning. 

Actually I was just circling back to say - I searched for anything in our style guide that references my claim of URL over Url and... nuthin! I could be mixing up or misremembering conversations, sorry if that's the case.  It seems easier to just follow Effective Dart hey, the problem is that we end up with code (where we access the Firebase APIs) that goes something like (eg.) photoUrl: firebaseUser.photoURL.  Personally I find `someURL` much more readable than `someUrl`, although I agree with their example that `HttpConnection` is clearer than `HTTPConnection`.  

I think my takeaway at this point is it's easier to just go with Effective Dart - changing our style guide based on different libraries seems like a bad idea.

2021-03-31 04:43 UTC, T-Davis commented on lib/middleware/app_middleware.dart
>  import 'package:the_process/middleware/auth/sign_in_with_google.dart';
Awesome, thanks for your input and talking it through again 👍

2021-03-31 04:46 UTC, T-Davis commented on test/redux/middleware_unit_test.dart
> +    }, skip: true);
This test is being skipped for the time being until we've finished the transition to null-safety. I've made a task in ClickUp to come back for it.

2021-03-31 04:48 UTC, T-Davis commented on test/redux/middleware_unit_test.dart
> +  group('Middleware catches errors', () {
Thanks mate! Good catch, I've updated the group name to 'Middleware ' so it reads more clearly. Definitely open if something comes to mind that you think sounds better.

2021-03-31 04:50 UTC, T-Davis commented on test/redux/middleware_unit_test.dart
> +      expect(store.dispatchedActions[0].runtimeType.toString(),
Great suggestion! That is def more clear (and less ugly). Here's what it's been changed to:
`expect(fakeStore.dispatchedActions.last is AddProblemAction, true);`

2021-03-31 05:22 UTC, nickmeinhold commented on test/redux/middleware_unit_test.dart
> +    }, skip: true);
Great, thanks!

2021-03-31 05:24 UTC, nickmeinhold approved these changes
Nice one Trev!  I learned a lot on this PR, thanks for the valuable discussions!

2021-03-31 05:24 UTC, merged